name: Deploy Laravel to AWS EC2

on:
  push:
    branches:
      - master  # Change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH and Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
          APP_DIR: /var/www/html/example-app1
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # Verify SSH connection (Debug Step)
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "echo 'SSH Connection Successful'"
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            cd $APP_DIR
            git pull origin master
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart apache2
          EOF
